<?php

return [

    'tags' => [
        'product-size' => [
            '5', '5.5', '6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '12', '13', '14', '15', '16', '17',
            '1.0C', '2.0C', '3.0C', '4.0C', '5.0C', '13.0C',
            '5W', '5.5W', '6W', '6.5W', '7W', '7.5W', '8W', '8.5W', '9W', '9.5W', '10W', '11W', '12W', '13W',
            '2XSMA', 'XSMA', 'SMALL', 'MED', 'LARGE', 'XLRG', '2XLRG',
            'ONESZ',
        ],
        'product-color' => [
            'BLACK', 'TAN', 'WHITE', 'GREEN', 'YELLOW', 'BLUE',
            'ORANGE', 'GREY', 'PINK', 'BROWN', 'SILVER', 'DENIM', 'TURQUOISE',
            'DARK GREY', 'LIGHT GREY', 'NAVY', 'OFF', 'GOLD', 'TAUPE', 'RED', 'MULTI',
        ],
        'product-delimiter' => ['/', ',', '&'],

        'gorgias-channel' => [
            'email', 'chat', 'help-center', 'facebook', 'facebook-messenger', 'facebook-recommendations', 'facebook mention',
            'instagram-ad-comment', 'instagram-comment', 'instagram-mention', 'instagram-direct-message',
        ],
        'gorgias-brand' => [
            'Steve Madden',
            'Steve Madden Canada',
            'Steve Madden Mexico',
            'Dolce Vita',
            'Dolce Vita Canada',
            'Dolce Vita Mexico',
            'Betsey Johnson',
            'Greats',
            'Blondo US',
            'Blondo Canada',
            'Superga',
            'BB Dakota',
        ],
        'gorgias-reason' => [
            '[Self service] Report issue - My order should have shipped by now',
            'Auto-response: order status',
            "[Help Center] Report issue - I'm past my expected delivery date",
            '[Help Center] Report issue - My order should have shipped by now',
            '[Help Center] Report issue - Where is my order?',
            'order_status',
            'Order Status',
            'order status question',
            'order status/tracking',
            "[Self service] Report issue - I'm past my expected delivery date",
            '[Self service] Report issue - Where is my order?',
            'Shipping Inquiry',
            'where-is-my-order',
            'Status of my order',
            'Auto-response: return',
            "[Help Center] Report issue - I'd like to return a product",
            "[Help Center] Report issue - I'd like to return the following items",
            'Request Return',
            'Request Return (auto)',
            'return',
            'Return help',
            'return-portal',
            'Return Question',
            "[Self Service] Report issue - I'd like to return a product",
            "[Self-Service] Report issue - I'd like to return a product",
            "[Self Service] Report issue - I'd like to return the following items",
            "[Self-Service] Report issue - I'd like to return the following items",
            'Address change',
            "[Help Center] Report issue - I'd like to change my shipping address",
            "[Help Center] Report issue - I'd like to change the delivery date",
            "[Help Center] Report issue - I'd like to edit my order",
            'Modify Order',
            "[Self Service] Report issue - I'd like to change my shipping address",
            "[Self-Service] Report issue - I'd like to change my shipping address",
            "[Self Service] Report issue - I'd like to change the delivery date",
            "[Self-Service] Report issue - I'd like to change the delivery date",
            "[Self Service] Report issue - I'd like to edit my order",
            "[Self-Service] Report issue - I'd like to edit my order",
            'Urgent order edit',
            '[Help Center] Report issue - My order was damaged in delivery',
            '[Help Center] Report issue - Some items are missing from my order',
            'order/damaged',
            '[Self Service] Report issue - My order was damaged in delivery',
            '[Self Service] Report issue - Some items are missing from my order',
            'Shipment lost/damaged',
            'SmartPost Issue',
            'Cancel Order (auto)',
            'Cancel Order (NOT Preorder)',
            'KNOX TOTE - Cancellation',
            "[Self-Service] Report issue cancel - I'd like to get a refund for this order",
            'simplr_cancel',
            'simplr_knox_cancel',
            'defective_item',
            '[Self Service] Report issue - The items in my order are defective',
            '[Help Center] Report issue - The items in my order are defective',
            'Return Issued',
            '[Self Service] Report issue - The items are different from what I ordered',
            '[Help Center] Report issue - The items are different from what I ordered',
            'Auto-response: exchange',
            'exchange',
            "[Help Center] Report issue - I'd like to exchange items in my order",
            "[Self Service] Report issue - I'd like to exchange items in my order",
            "[Self-Service] Report issue - I'd like to exchange items in my order",
            'KNOX TOTE - Complaint',
            'Handbags Delay',
            'Preorder Delay',
            'simplr_knox_delay',
            'BSUMMIT Delay',
            'CONTAINER Delay',
            'Discounts/promotions',
            '[Help Center] Report issue - I forgot to apply my discount code',
            'Promo Question',
            '[Self Service] How can I get a discount?',
            '[Self-Service] Promo product & other questions',
            '[Self-Service] Report issue - I forgot to apply my discount code',
            'Product Inquiry',
            'product & other questions',
            '[Self Service] Are your products waterproof?',
            'Interested in a product',
            'Auto-response: refund status',
            "[Help Center] Report issue - I didn't get my refund",
            'Refund',
            'Refund Status',
            "[Self-Service] Report issue - I didn't get my refund",
            "[Help Center] Report issue - I'd like to get a refund for this order",
            "[Self Service] Report issue - I'd like to get a refund for this order",
            "[Self-Service] Report issue - I'd like to get a refund for this order",
            'Order issue',
            'Order Issue',
            'other',
            'Other',
            'Place Order',
            '[Self Service] Report issue - I’d like to reorder some items',
            '[Self-Service] Report issue - I’d like to reorder some items',
            'Policy Question',
            '[Self Service] What is your shipping policy?',
            'shipping policy',
            'password/reset',
            'order/account help',
            'Retail/Wholesale Product Issues',
            'StoreCustomers',
            'spare parts',
            'wholesale',
            'Unaware PREORDER',
            'SignupCode not received',
            'Return not procesed',
            'Return label not received',
            'Complaint about restocking fee - SMCA',
            'Return Declined – Too Late',
            'Return Declined – Clearance',
            'Recurate',
            'PreOrder ETA',
            'Order Ship Late',
            'Never Shipped – warehouses',
            'Never Shipped – stores',
            'Loyalty Question',
            'Loyalty Delayed',
            'Late Pick-UP',
            'Inventory Inquiry',
            'Escalated Matter',
            'Corporate issue',
            'Chargeback',
            'CCPA',
            'Cancel Preorder',
        ],

    ],

    'reports' => [
        ['name' => 'Agents overview', 'type' => 'Mixed', 'slug' => 'agents-overview'],
        ['name' => 'Service Level', 'type' => 'Talkdesk', 'slug' => 'service-level'],
        ['name' => 'Agent Data', 'type' => 'Talkdesk', 'slug' => 'agent-data'],
        ['name' => 'Best sellers', 'type' => 'Shopify', 'slug' => 'best-sellers'],
        ['name' => 'Appeasements breakdown', 'type' => 'Shopify', 'slug' => 'appeasements-breakdown'],
        ['name' => 'Never shipped', 'type' => 'Shopify', 'slug' => 'never-shipped'],
        ['name' => 'In-store returns & unlocks', 'type' => 'Shopify', 'slug' => 'in-store-returns-unlocks'],
        ['name' => 'Reasons for contact', 'type' => 'Gorgias', 'slug' => 'reasons-for-contact'],
        ['name' => 'Appeasements per month', 'type' => 'Shopify', 'slug' => 'appeasements-per-month'],
    ],
    'brands' => [
        [
            'name' => 'Steve Madden US',
            'shorthand' => 'SMUS',
            'tags' => ['smus', 'sm_loyalty'],
        ],
        [
            'name' => 'Steve Madden Canada',
            'shorthand' => 'SMCA',
            'tags' => ['smca_en', 'smca_fr'],
        ],
        [
            'name' => 'Steve Madden Mexico',
            'shorthand' => 'SMMX',
            'tags' => ['smmx'],
        ],
        [
            'name' => 'Betsey Johnson',
            'shorthand' => 'BJ',
            'tags' => ['bj'],
        ],
        [
            'name' => 'Dolce Vita US',
            'shorthand' => 'DVUS',
            'tags' => ['dvus'],
        ],
        [
            'name' => 'Dolce Vita Canada',
            'shorthand' => 'DVCA',
            'tags' => ['dvca_en', 'dvca_fr'],
        ],
        [
            'name' => 'Dolce Vita Mexico',
            'shorthand' => 'DVMX',
            'tags' => ['dvmx'],
        ],
        [
            'name' => 'GREATS',
            'shorthand' => 'GR',
            'tags' => ['greats'],
        ],
        [
            'name' => 'Blondo US',
            'shorthand' => 'BLUS',
            'tags' => ['blus'],
        ],
        [
            'name' => 'Blondo Canada',
            'shorthand' => 'BLCA',
            'tags' => ['blca_en', 'blca_fr'],
        ],
        [
            'name' => 'Superga USA',
            'shorthand' => 'SU',
            'tags' => ['su'],
        ],
        [
            'name' => 'BB Dakota',
            'shorthand' => 'BB',
            'tags' => ['bbdakota'],
        ],
        [
            'name' => 'ATM Collection',
            'shorthand' => 'ATM',
            'tags' => ['atm'],
        ],
    ],

    'collections' => [
        [
            'name' => "Women's Shoes",
            'minimum_quantity' => 1,
            'threshold' => 120,
        ],
        [
            'name' => "Women's Clothing",
            'minimum_quantity' => 6,
            'threshold' => 60,
        ],
        [
            'name' => "Kid's Shoes",
            'minimum_quantity' => 6,
            'threshold' => 30,
        ],
        [
            'name' => "Men's Shoes",
            'minimum_quantity' => 6,
            'threshold' => 60,
        ],
        [
            'name' => 'Bags & Accessories',
            'minimum_quantity' => 6,
            'threshold' => 60,
        ],
    ],
    'categories' => [
        [
            'name' => "Women's Shoes",
        ],
        [
            'name' => "Women's Clothing",
        ],
        [
            'name' => "Kid's Shoes",
        ],
        [
            'name' => "Men's Shoes",
        ],
        [
            'name' => 'Handbags',
        ],
        [
            'name' => 'Accessories',
        ],
    ],
    'appeasement-reasons' => [
        [
            'name' => 'Tracer',
            'shorthand' => 'TR',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'In-store return',
            'shorthand' => 'IR',
            'has_percentage' => false,
            'has_location' => true,
            'has_product' => true,
            'has_size' => true,
        ],
        [
            'name' => 'Shipping delay',
            'shorthand' => 'SD',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Restocking fee',
            'shorthand' => 'RF',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Never Shipped',
            'shorthand' => 'NS',
            'has_percentage' => false,
            'has_location' => true,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Worn/Damaged',
            'shorthand' => 'WD',
            'has_percentage' => true,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Missed promotion',
            'shorthand' => 'MP',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Price adjustment',
            'shorthand' => 'PA',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Manufacturer\'s defect',
            'shorthand' => 'MD',
            'has_percentage' => true,
            'has_location' => false,
            'has_product' => true,
            'has_size' => false,
        ],
        [
            'name' => 'Afterpay tracer',
            'shorthand' => 'APTR',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Klarna tracer',
            'shorthand' => 'KTR',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Shop Pay Installments tracer',
            'shorthand' => 'STR',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Incomplete shipment',
            'shorthand' => 'INC',
            'has_percentage' => false,
            'has_location' => true,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Lost in transit',
            'shorthand' => 'LIT',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Other',
            'shorthand' => 'OTHER',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Shipping problems',
            'shorthand' => 'SP',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Wrong Item',
            'shorthand' => 'WI',
            'has_percentage' => true,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Empty box',
            'shorthand' => 'EB',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Cancelled but not refunded',
            'shorthand' => 'CR',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'International error',
            'shorthand' => 'INTL',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Unlocks',
            'shorthand' => 'UN',
            'has_percentage' => false,
            'has_location' => true,
            'has_product' => true,
            'has_size' => true,
        ],
        [
            'name' => 'Delivery delay',
            'shorthand' => 'DD',
            'has_percentage' => true,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Cancelled item',
            'shorthand' => 'CI',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Damaged in transit',
            'shorthand' => 'DIT',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'PreOrder delay',
            'shorthand' => 'PD',
            'has_percentage' => true,
            'has_location' => false,
            'has_product' => true,
            'has_size' => false,
        ],
        [
            'name' => 'Price match',
            'shorthand' => 'PM',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Mismates',
            'shorthand' => 'MM',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Out of stock',
            'shorthand' => 'OOS',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Recurate',
            'shorthand' => 'RECURATE',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Riskified declined',
            'shorthand' => 'RD',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Return received',
            'shorthand' => 'RR',
            'has_percentage' => false,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
        [
            'name' => 'Clearance',
            'shorthand' => 'CLP',
            'has_percentage' => true,
            'has_location' => false,
            'has_product' => false,
            'has_size' => false,
        ],
    ],

    'locations' => [
        ['number' => 1, 'name' => 'Store 1', 'type' => 'store', 'parent_id' => null],
        ['number' => 2, 'name' => 'Store 2', 'type' => 'store', 'parent_id' => null],
        ['number' => 3, 'name' => 'Store 3', 'type' => 'store', 'parent_id' => null],
        ['number' => 4, 'name' => 'Store 4', 'type' => 'store', 'parent_id' => null],
        ['number' => 5, 'name' => 'Store 5', 'type' => 'store', 'parent_id' => null],
        ['number' => 7, 'name' => 'Store 7', 'type' => 'store', 'parent_id' => null],
        ['number' => 9, 'name' => 'Store 9', 'type' => 'store', 'parent_id' => null],
        ['number' => 10, 'name' => 'Store 10', 'type' => 'store', 'parent_id' => null],
        ['number' => 14, 'name' => 'Store 14', 'type' => 'store', 'parent_id' => null],
        ['number' => 15, 'name' => 'Store 15', 'type' => 'store', 'parent_id' => null],
        ['number' => 17, 'name' => 'Store 17', 'type' => 'store', 'parent_id' => null],
        ['number' => 19, 'name' => 'Store 19', 'type' => 'store', 'parent_id' => null],
        ['number' => 22, 'name' => 'Store 22', 'type' => 'store', 'parent_id' => null],
        ['number' => 25, 'name' => 'Store 25', 'type' => 'store', 'parent_id' => null],
        ['number' => 28, 'name' => 'Store 28', 'type' => 'store', 'parent_id' => null],
        ['number' => 38, 'name' => 'Store 38', 'type' => 'store', 'parent_id' => null],
        ['number' => 42, 'name' => 'Store 42', 'type' => 'store', 'parent_id' => null],
        ['number' => 45, 'name' => 'Store 45', 'type' => 'store', 'parent_id' => null],
        ['number' => 50, 'name' => 'Store 50', 'type' => 'store', 'parent_id' => null],
        ['number' => 56, 'name' => 'Store 56', 'type' => 'store', 'parent_id' => null],
        ['number' => 57, 'name' => 'Store 57', 'type' => 'store', 'parent_id' => null],
        ['number' => 70, 'name' => 'Store 70', 'type' => 'store', 'parent_id' => null],
        ['number' => 71, 'name' => 'Store 71', 'type' => 'store', 'parent_id' => null],
        ['number' => 72, 'name' => 'Store 72', 'type' => 'store', 'parent_id' => null],
        ['number' => 75, 'name' => 'Store 75', 'type' => 'store', 'parent_id' => null],
        ['number' => 77, 'name' => 'Store 77', 'type' => 'store', 'parent_id' => null],
        ['number' => 78, 'name' => 'Store 78', 'type' => 'store', 'parent_id' => null],
        ['number' => 79, 'name' => 'Store 79', 'type' => 'store', 'parent_id' => null],
        ['number' => 81, 'name' => 'Store 81', 'type' => 'store', 'parent_id' => null],
        ['number' => 82, 'name' => 'Store 82', 'type' => 'store', 'parent_id' => null],
        ['number' => 83, 'name' => 'Store 83', 'type' => 'store', 'parent_id' => null],
        ['number' => 85, 'name' => 'Store 85', 'type' => 'store', 'parent_id' => null],
        ['number' => 100, 'name' => 'Store 100', 'type' => 'store', 'parent_id' => null],
        ['number' => 102, 'name' => 'Store 102', 'type' => 'store', 'parent_id' => null],
        ['number' => 103, 'name' => 'Store 103', 'type' => 'store', 'parent_id' => null],
        ['number' => 104, 'name' => 'Store 104', 'type' => 'store', 'parent_id' => null],
        ['number' => 120, 'name' => 'Store 120', 'type' => 'store', 'parent_id' => null],
        ['number' => 121, 'name' => 'Store 121', 'type' => 'store', 'parent_id' => null],
        ['number' => 124, 'name' => 'Store 124', 'type' => 'store', 'parent_id' => null],
        ['number' => 126, 'name' => 'Store 126', 'type' => 'store', 'parent_id' => null],
        ['number' => 128, 'name' => 'Store 128', 'type' => 'store', 'parent_id' => null],
        ['number' => 129, 'name' => 'Store 129', 'type' => 'store', 'parent_id' => null],
        ['number' => 132, 'name' => 'Store 132', 'type' => 'store', 'parent_id' => null],
        ['number' => 133, 'name' => 'Store 133', 'type' => 'store', 'parent_id' => null],
        ['number' => 134, 'name' => 'Store 134', 'type' => 'store', 'parent_id' => null],
        ['number' => 135, 'name' => 'Store 135', 'type' => 'store', 'parent_id' => null],
        ['number' => 137, 'name' => 'Store 137', 'type' => 'store', 'parent_id' => null],
        ['number' => 138, 'name' => 'Store 138', 'type' => 'store', 'parent_id' => null],
        ['number' => 140, 'name' => 'Store 140', 'type' => 'store', 'parent_id' => null],
        ['number' => 145, 'name' => 'Store 145', 'type' => 'store', 'parent_id' => null],
        ['number' => 147, 'name' => 'Store 147', 'type' => 'store', 'parent_id' => null],
        ['number' => 148, 'name' => 'Store 148', 'type' => 'store', 'parent_id' => null],
        ['number' => 149, 'name' => 'Store 149', 'type' => 'store', 'parent_id' => null],
        ['number' => 150, 'name' => 'Store 150', 'type' => 'store', 'parent_id' => null],
        ['number' => 151, 'name' => 'Store 151', 'type' => 'store', 'parent_id' => null],
        ['number' => 253, 'name' => 'Store 253', 'type' => 'store', 'parent_id' => null],
        ['number' => 254, 'name' => 'Store 254', 'type' => 'store', 'parent_id' => null],
        ['number' => 255, 'name' => 'Store 255', 'type' => 'store', 'parent_id' => null],
        ['number' => 256, 'name' => 'Store 256', 'type' => 'store', 'parent_id' => null],
        ['number' => 257, 'name' => 'Store 257', 'type' => 'store', 'parent_id' => null],
        ['number' => 510, 'name' => 'Store 510', 'type' => 'store', 'parent_id' => null],
        ['number' => 512, 'name' => 'Store 512', 'type' => 'store', 'parent_id' => null],
        ['number' => 513, 'name' => 'Store 513', 'type' => 'store', 'parent_id' => null],
        ['number' => 514, 'name' => 'Store 514', 'type' => 'store', 'parent_id' => null],
        ['number' => 516, 'name' => 'Store 516', 'type' => 'store', 'parent_id' => null],
        ['number' => 517, 'name' => 'Store 517', 'type' => 'store', 'parent_id' => null],
        ['number' => 518, 'name' => 'Store 518', 'type' => 'store', 'parent_id' => null],
        ['number' => 519, 'name' => 'Store 519', 'type' => 'store', 'parent_id' => null],
        ['number' => 520, 'name' => 'Store 520', 'type' => 'store', 'parent_id' => null],
        ['number' => 523, 'name' => 'Store 523', 'type' => 'store', 'parent_id' => null],
        ['number' => 524, 'name' => 'Store 524', 'type' => 'store', 'parent_id' => null],
        ['number' => 525, 'name' => 'Store 525', 'type' => 'store', 'parent_id' => null],
        ['number' => 526, 'name' => 'Store 526', 'type' => 'store', 'parent_id' => null],
        ['number' => 527, 'name' => 'Store 527', 'type' => 'store', 'parent_id' => null],
        ['number' => 529, 'name' => 'Store 529', 'type' => 'store', 'parent_id' => null],
        ['number' => 530, 'name' => 'Store 530', 'type' => 'store', 'parent_id' => null],
        ['number' => 531, 'name' => 'Store 531', 'type' => 'store', 'parent_id' => null],
        ['number' => 532, 'name' => 'Store 532', 'type' => 'store', 'parent_id' => null],
        ['number' => 533, 'name' => 'Store 533', 'type' => 'store', 'parent_id' => null],
        ['number' => 535, 'name' => 'Store 535', 'type' => 'store', 'parent_id' => null],
        ['number' => 536, 'name' => 'Store 536', 'type' => 'store', 'parent_id' => null],
        ['number' => 537, 'name' => 'Store 537', 'type' => 'store', 'parent_id' => null],
        ['number' => 538, 'name' => 'Store 538', 'type' => 'store', 'parent_id' => null],
        ['number' => 539, 'name' => 'Store 539', 'type' => 'store', 'parent_id' => null],
        ['number' => 541, 'name' => 'Store 541', 'type' => 'store', 'parent_id' => null],
        ['number' => 542, 'name' => 'Store 542', 'type' => 'store', 'parent_id' => null],
        ['number' => 543, 'name' => 'Store 543', 'type' => 'store', 'parent_id' => null],
        ['number' => 544, 'name' => 'Store 544', 'type' => 'store', 'parent_id' => null],
        ['number' => 546, 'name' => 'Store 546', 'type' => 'store', 'parent_id' => null],
        ['number' => 547, 'name' => 'Store 547', 'type' => 'store', 'parent_id' => null],
        ['number' => 549, 'name' => 'Store 549', 'type' => 'store', 'parent_id' => null],
        ['number' => 550, 'name' => 'Store 550', 'type' => 'store', 'parent_id' => null],
        ['number' => 551, 'name' => 'Store 551', 'type' => 'store', 'parent_id' => null],
        ['number' => 552, 'name' => 'Store 552', 'type' => 'store', 'parent_id' => null],
        ['number' => 553, 'name' => 'Store 553', 'type' => 'store', 'parent_id' => null],
        ['number' => 554, 'name' => 'Store 554', 'type' => 'store', 'parent_id' => null],
        ['number' => 555, 'name' => 'Store 555', 'type' => 'store', 'parent_id' => null],
        ['number' => 556, 'name' => 'Store 556', 'type' => 'store', 'parent_id' => null],
        ['number' => 557, 'name' => 'Store 557', 'type' => 'store', 'parent_id' => null],
        ['number' => 558, 'name' => 'Store 558', 'type' => 'store', 'parent_id' => null],
        ['number' => 559, 'name' => 'Store 559', 'type' => 'store', 'parent_id' => null],
        ['number' => 560, 'name' => 'Store 560', 'type' => 'store', 'parent_id' => null],
        ['number' => 562, 'name' => 'Store 562', 'type' => 'store', 'parent_id' => null],
        ['number' => 563, 'name' => 'Store 563', 'type' => 'store', 'parent_id' => null],
        ['number' => 564, 'name' => 'Store 564', 'type' => 'store', 'parent_id' => null],
        ['number' => 565, 'name' => 'Store 565', 'type' => 'store', 'parent_id' => null],
        ['number' => 567, 'name' => 'Store 567', 'type' => 'store', 'parent_id' => null],
        ['number' => 568, 'name' => 'Store 568', 'type' => 'store', 'parent_id' => null],
        ['number' => 571, 'name' => 'Store 571', 'type' => 'store', 'parent_id' => null],
        ['number' => 572, 'name' => 'Store 572', 'type' => 'store', 'parent_id' => null],
        ['number' => 574, 'name' => 'Store 574', 'type' => 'store', 'parent_id' => null],
        ['number' => 575, 'name' => 'Store 575', 'type' => 'store', 'parent_id' => null],
        ['number' => 576, 'name' => 'Store 576', 'type' => 'store', 'parent_id' => null],
        ['number' => 577, 'name' => 'Store 577', 'type' => 'store', 'parent_id' => null],
        ['number' => 902, 'name' => 'Warehouse 902', 'type' => 'warehouse', 'parent_id' => null],
        ['number' => 904, 'name' => 'Warehouse 904', 'type' => 'warehouse', 'parent_id' => null],
        ['number' => 905, 'name' => 'Warehouse 905', 'type' => 'warehouse', 'parent_id' => null],
        ['number' => 906, 'name' => 'Warehouse 906', 'type' => 'warehouse', 'parent_id' => null],
        ['number' => 907, 'name' => 'Warehouse 907', 'type' => 'warehouse', 'parent_id' => null],
        ['number' => 924, 'name' => 'Warehouse 924', 'type' => 'warehouse', 'parent_id' => 67],
        ['number' => 925, 'name' => 'Warehouse 925', 'type' => 'warehouse', 'parent_id' => 68],
        ['number' => 975, 'name' => 'Warehouse 975', 'type' => 'warehouse', 'parent_id' => 68],
        ['number' => 946, 'name' => 'Warehouse 946', 'type' => 'warehouse', 'parent_id' => 69],
        ['number' => 976, 'name' => 'Warehouse 976', 'type' => 'warehouse', 'parent_id' => 69],
        ['number' => 977, 'name' => 'Warehouse 977', 'type' => 'warehouse', 'parent_id' => 70],
        ['number' => 922, 'name' => 'Warehouse 922', 'type' => 'warehouse', 'parent_id' => 66],
        ['number' => 972, 'name' => 'Warehouse 972', 'type' => 'warehouse', 'parent_id' => 66],
    ],

    'dispositions' => [
        ['name' => 'Account help'],
        ['name' => 'Cancel Order'],
        ['name' => 'Cancel PreOrder'],
        ['name' => 'CCPA'],
        ['name' => 'Chargeback'],
        ['name' => 'Corporate issue'],
        ['name' => 'Escalated Matter'],
        ['name' => 'Exchange'],
        ['name' => 'Inventory Inquiry'],
        ['name' => 'Late Pick-UP'],
        ['name' => 'Loyalty Delayed'],
        ['name' => 'Loyalty Question'],
        ['name' => 'Modify Order'],
        ['name' => 'Never Shipped – warehouses'],
        ['name' => 'Never Shipped – stores'],
        ['name' => 'Order Ship Late'],
        ['name' => 'Other'],
        ['name' => 'Place Order'],
        ['name' => 'Policy Question'],
        ['name' => 'Preorder Delay'],
        ['name' => 'PreOrder ETA'],
        ['name' => 'Product Inquiry'],
        ['name' => 'Promo Question'],
        ['name' => 'Recurate'],
        ['name' => 'Refund Inquiry'],
        ['name' => 'Complaint about restocking fee - SMCA'],
        ['name' => 'Retail/Wholesale Product Issues'],
        ['name' => 'Return Declined – Clearance'],
        ['name' => 'Return Declined – Too Late'],
        ['name' => 'Return Issued'],
        ['name' => 'Return label not received'],
        ['name' => 'Return not processed'],
        ['name' => 'Return Question'],
        ['name' => 'Shipment lost/damaged'],
        ['name' => 'Shipping Inquiry'],
        ['name' => 'SignupCode not received'],
        ['name' => 'Spare Parts'],
        ['name' => 'Status of my order'],
        ['name' => 'Unaware PREORDER'],
        ['name' => 'Wholesale'],
    ],

];
